import Head from "next/head";
import { useRouter } from "next/router";
import styles from "../../styles/Home.module.css";

function Friends({ id }) {
  const router = useRouter();

  return (
    <div className={styles.container}>
      <Head>
        <title>Friends</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Friends page. Your id is: {id}
        </h1>
        <ul>
          <li>
            <a href="/">Go Home</a>
          </li>
          <li>
            <a href="/login">Go To Login</a>
          </li>
        </ul>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}

export async function getServerSideProps({ params }) {
  return {
    props: { id: params.id }, // will be passed to the page component as props
  };
}

export default Friends;
