import Head from "next/head";
import { useRouter } from "next/router";
import styles from "../../styles/Home.module.css";

function Profile({ user }) {
  const router = useRouter();

  return (
    <div className={styles.container}>
      <Head>
        <title>Profile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to user: {user}'s profile</h1>
        <ul>
          <li>
            <a href="/">Go Home</a>
          </li>
          <li>
            <a href="/login">Go To Login</a>
          </li>
          <li>
            <a href="/friends/lkajsdg8">Go To Friends</a>
          </li>
        </ul>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}

export async function getServerSideProps({ params }) {
  return {
    props: { user: params.user }, // will be passed to the page component as props
  };
}

export default Profile;
